### ISSUE TITLE
CDK Deploy Error - invalid signature

### ISSUE THREAD

**Issue by kennycason** [aws-containers/Airflow-on-Fargate#10]
Our team was trying to setup Airflow through the following steps via CDK:

https://aws.amazon.com/blogs/containers/running-airflow-on-aws-fargate/

However, during the `cdk deploy` step, and after answering "yes" to the prompt, we are encountering the following error:
```
#5 [2/7] RUN apt-get update && apt-get install -y python3-pip     libcurl4-gnutls-dev     librtmp-dev     python3-dev     libpq-dev
#5 sha256:787088182aea3ef729295dade2fab650429db33d33b8265ed2abda11ad49abff
#5 0.327 + apt-get update
#5 0.568 Get:1 http://security.debian.org/debian-security buster/updates InRelease [34.8 kB]
#5 0.580 Get:2 http://deb.debian.org/debian buster InRelease [122 kB]
#5 0.633 Get:3 http://deb.debian.org/debian buster-updates InRelease [56.6 kB]
#5 0.715 Get:4 http://repo.mysql.com/apt/debian stretch InRelease [21.6 kB]
#5 0.769 Get:5 http://security.debian.org/debian-security buster/updates/main amd64 Packages [508 kB]
#5 0.916 Get:6 http://deb.debian.org/debian buster/main amd64 Packages [7909 kB]
#5 1.216 Get:7 http://deb.debian.org/debian buster-updates/main amd64 Packages [8788 B]
#5 1.227 Err:4 http://repo.mysql.com/apt/debian stretch InRelease
#5 1.227   The following signatures were invalid: EXPKEYSIG 8C718D3B5072E1F5 MySQL Release Engineering <mysql-build@oss.oracle.com>
#5 2.403 Reading package lists...
#5 3.271 W: GPG error: http://repo.mysql.com/apt/debian stretch InRelease: The following signatures were invalid: EXPKEYSIG 8C718D3B5072E1F5 MySQL Release Engineering <mysql-build@oss.oracle.com>
#5 3.271 E: The repository 'http://repo.mysql.com/apt/debian stretch InRelease' is not signed.
#5 ERROR: executor failed running [/bin/bash -o pipefail -e -u -x -c apt-get update && apt-get install -y python3-pip     libcurl4-gnutls-dev     librtmp-dev     python3-dev     libpq-dev]: exit code: 100
------
executor failed running [/bin/bash -o pipefail -e -u -x -c apt-get update && apt-get install -y python3-pip     libcurl4-gnutls-dev     librtmp-dev     python3-dev     libpq-dev]: exit code: 100

 ❌  FarFlow failed: Error: Failed to publish one or more assets. See the error messages above for more information.
    at publishAssets (/Users/<REDACTED>/.nvm/versions/node/v16.14.2/lib/node_modules/aws-cdk/lib/index.js:391:74837)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async deployStack (/Users/<REDACTED>/.nvm/versions/node/v16.14.2/lib/node_modules/aws-cdk/lib/index.js:393:390)
    at async Object.deployStack2 [as deployStack] (/Users/<REDACTED>/.nvm/versions/node/v16.14.2/lib/node_modules/aws-cdk/lib/index.js:400:149977)
    at async /Users/<REDACTED>/.nvm/versions/node/v16.14.2/lib/node_modules/aws-cdk/lib/index.js:400:135508
```

Do you have any insight as to how to solve this problem? Thanks!

**Comment by kennycason** [comment]
Update: Note that updating the Dockerfile to:
```
FROM apache/airflow:2.6.1
```
Solved the issue. Our next issue is that we have exceeded our VPC quota limit and are going to attempt to modify the CDK code to operate within our existing VPC.
